# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "vebdew"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Liu"]
  s.date = "2012-03-14"
  s.description = "Generate HTML5 slides"
  s.email = "andrewliu33@gmail.com"
  s.executables = ["vebdew"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/vebdew",
    "lib/template/config.ru",
    "lib/template/css/images/ui-bg_flat_0_aaaaaa_40x100.png",
    "lib/template/css/images/ui-bg_glass_95_fef1ec_1x400.png",
    "lib/template/css/images/ui-bg_gloss-wave_16_121212_500x100.png",
    "lib/template/css/images/ui-bg_highlight-hard_15_888888_1x100.png",
    "lib/template/css/images/ui-bg_highlight-hard_55_555555_1x100.png",
    "lib/template/css/images/ui-bg_highlight-soft_35_adadad_1x100.png",
    "lib/template/css/images/ui-bg_highlight-soft_60_dddddd_1x100.png",
    "lib/template/css/images/ui-bg_inset-soft_15_121212_1x100.png",
    "lib/template/css/images/ui-icons_666666_256x240.png",
    "lib/template/css/images/ui-icons_aaaaaa_256x240.png",
    "lib/template/css/images/ui-icons_bbbbbb_256x240.png",
    "lib/template/css/images/ui-icons_c98000_256x240.png",
    "lib/template/css/images/ui-icons_cccccc_256x240.png",
    "lib/template/css/images/ui-icons_cd0a0a_256x240.png",
    "lib/template/css/images/ui-icons_f29a00_256x240.png",
    "lib/template/css/jquery-ui.css",
    "lib/template/css/main.css",
    "lib/template/css/reset.css",
    "lib/template/css/ruler.css",
    "lib/template/css/sample.css",
    "lib/template/css/styles.css",
    "lib/template/js/index.js",
    "lib/template/js/init.js",
    "lib/template/js/jquery-ui.min.js",
    "lib/template/js/jquery.min.js",
    "lib/template/js/reveal.js",
    "lib/template/js/ruler.js",
    "lib/template/js/sample.js",
    "lib/template/vew/sample.vew",
    "lib/template/vew/template.erb",
    "lib/vebdew.rb",
    "lib/vebdew/formatter.rb",
    "lib/vebdew/parser.rb",
    "lib/vebdew/runner.rb",
    "test/test_parser.rb",
    "vebdew.gemspec"
  ]
  s.homepage = "http://github.com/eggegg/vebdew"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "HTML5 slides generator"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<erubis>, [">= 0"])
      s.add_runtime_dependency(%q<htmlentities>, [">= 0"])
      s.add_development_dependency(%q<bacon>, ["~> 1.1.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<erubis>, [">= 0"])
      s.add_dependency(%q<htmlentities>, [">= 0"])
      s.add_dependency(%q<bacon>, ["~> 1.1.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<erubis>, [">= 0"])
    s.add_dependency(%q<htmlentities>, [">= 0"])
    s.add_dependency(%q<bacon>, ["~> 1.1.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

